version: 0.1.3.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: build.cmd
artifacts:
- path: pkg\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: knxgwH5a9amElcEhLWera7bfkrOIO5YFQvDuJ9T7nN93bsbarPSWfaRM05nsu5iE